stages:
  - build
  - test

variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

cache:
  paths:
    - .m2/repository

image: maven:latest

build:
  stage: build
  script:
    - echo "Starting the checkstyle"
    - mvn checkstyle:check
    - echo "Starting the project build"
    - mvn clean install -DskipTests
  only:
    - merge_request

test:
  stage: test
  script:
    - echo "Beginning project integration testing"
    - mvn clean test
    - cat target/site/jacoco/index.html | grep -o 'Total[^%]*%'
  coverage: '/Total.*?([0-9]{1,3})%/'
  only:
    - merge_request
  dependencies:
    - build